apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pustaka
  template:
    metadata:
      labels:
        app: api-gateway-pustaka
    spec:
      containers:
        - name: api-gateway-pustaka
          image: furqonaugustseventeenth/praktek-api-gateway-pustaka:1.0
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "API-GATEWAY-PUSTAKA"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "API-GATEWAY-PUSTAKA:9002"
            - name: SERVER_PORT
              value: "9002"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-pustaka
spec:
  selector:
    app: api-gateway-pustaka
  ports:
    - port: 9002
      targetPort: 9002
