apiVersion: apps/v1
kind: Deployment
metadata:
  name: peminjaman-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peminjaman-service
  template:
    metadata:
      labels:
        app: peminjaman-service
    spec:
      containers:
        - name: peminjaman-service
          image: furqonaugustseventeenth/praktek-peminjaman-service:1.0
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-pustaka:5432/peminjaman
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres

            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-pustaka:27017/peminjaman

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "PEMINJAMAN-SERVICE"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "PEMINJAMAN-SERVICE:8006"
            - name: SPRING_APPLICATION_NAME
              value: "peminjaman-service"
            - name: SERVER_PORT
              value: "8086"
---
apiVersion: v1
kind: Service
metadata:
  name: peminjaman-service
spec:
  selector:
    app: peminjaman-service
  ports:
    - port: 8086
      targetPort: 8086
