name: toko-service
services:

  eureka:
    image: eureka-service:1.0
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - service_network

  api-gateway:
    image: api-gateway:1.1
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - eureka
    networks:
      - service_network

  produk-service:
    image: produk-service:1.1
    container_name: produk-service
    depends_on:
      - eureka
    networks:
      - service_network

  pelanggan-service:
    image: pelanggan-service:1.1
    container_name: pelanggan-service
    depends_on:
      - eureka
    networks:
      - service_network

  order-service:
    image: order-service:1.1
    container_name: order-service
    depends_on:
      - eureka
    networks:
      - service_network

networks:
  service_network:
    external: true
