apiVersion: apps/v1
kind: Deployment
metadata:
  name: anggota-service
  namespace: pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anggota-service
  template:
    metadata:
      labels:
        app: anggota-service
    spec:
      containers:
        - name: anggota-service
          image: anggota-service:latest   # di-build dari Jenkins nanti
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:/app/data/anggota
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
          volumeMounts:
            - name: anggota-data
              mountPath: /app/data
            - name: anggota-logs
              mountPath: /app/logs
      volumes:
        - name: anggota-data
          emptyDir: {}  # bisa dibuat PVC jika mau persistent
        - name: anggota-logs
          emptyDir: {}
