apiVersion: v1
kind: Service
metadata:
  name: eureka-pustaka
spec:
  selector:
    app: eureka-pustaka
  ports:
    - port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-pustaka
  template:
    metadata:
      labels:
        app: eureka-pustaka
    spec:
      containers:
        - name: eureka-pustaka
          image: steeltoeoss/eureka-server
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_OPTS
              value: "-Xmx256m -Xss512k"
          livenessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:8761"]
            initialDelaySeconds: 30
            periodSeconds: 30