apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-pustaka
  namespace: pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pustaka
  template:
    metadata:
      labels:
        app: api-gateway-pustaka
    spec:
      containers:
        - name: api-gateway
          image: api-gateway-pustaka:latest
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SERVER_PORT
              value: "9002"
            - name: LOGGING_FILE_NAME
              value: /app/logs/gateway-service.log
          volumeMounts:
            - name: gateway-logs
              mountPath: /app/logs
      volumes:
        - name: gateway-logs
          emptyDir: {}
