apiVersion: v1
kind: Service
metadata:
  name: api-gateway-pustaka
  namespace: pustaka
spec:
  selector:
    app: api-gateway-pustaka
  ports:
    - port: 9002
      targetPort: 9002
  type: NodePort
