apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-pustaka
  namespace: pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: steeltoeoss/eureka-server
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_OPTS
              value: "-Xmx256m -Xss512k"
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            periodSeconds: 10
            initialDelaySeconds: 15
