apiVersion: apps/v1
kind: Deployment
metadata:
  name: buku-service
  namespace: pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buku-service
  template:
    metadata:
      labels:
        app: buku-service
    spec:
      containers:
        - name: buku-service
          image: buku-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password

            # H2 Database
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:/app/data/buku
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password

            - name: SERVER_PORT
              value: "8085"

            - name: LOGGING_FILE_NAME
              value: /app/logs/buku-service.log
          volumeMounts:
            - name: buku-data
              mountPath: /app/data
            - name: buku-logs
              mountPath: /app/logs
      volumes:
        - name: buku-data
          emptyDir: {}
        - name: buku-logs
          emptyDir: {}
