spring:
  application:
    name: peminjaman-service
  datasource:
    url: jdbc:postgresql://localhost:5433/peminjaman
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '@Furqon_123'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/peminjaman
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    template:
      exchange: peminjaman.exchange
    listener:
      simple:
        default-requeue-rejected: false

app:
  rabbitmq:
    queue:
      transaction: peminjaman.queue.transaction
      email: peminjaman.queue.email
    exchange: peminjaman.exchange
    routing-key: 
      transaction: peminjaman.routing.key.transaction
      email: peminjaman.routing.key.email

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "your email"
    from: "your email"
    password: "your password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    '[com.furqon.peminjaman_service]': DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8086